name: Feature Request
description: Propose an improvement
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: textarea
    attributes:
      label: Problem
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed solution
    validations:
      required: true
